### ISSUE TITLE
HUD Issue

### ISSUE THREAD

**Issue by KacperOtreba** [PerzotProgrammer/SummerSmash#1]
Po zgonie grę można zapauzować i po powrocie do ekranu zgonu HUD gracza powraca.
Dodałbym jeszcze możliwość do powrotu do lobby po śmierci.
Pozdrawiam

**Comment by KacperOtreba** [comment]
Dobrze, zajmiemy się tym w godzinach pracy.
Dziękuję za współpracę i proszę o cierpliwość.
Pozdrawiam Kacper.

**Comment by PerzotProgrammer** [comment]
Lekkie symptomy Alzheimera objawiają się zanikami pamięci.
Lekkie symptomy Alzheimera objawiają się zanikami pamięci.
Lekkie symptomy Alzheimera objawiają się zanikami pamięci.
Lekkie symptomy Alzheimera objawiają się zanikami pamięci.
Lekkie symptomy Alzheimera objawiają się zanikami pamięci.
Lekkie symptomy Alzheimera objawiają się zanikami pamięci.
Lekkie symptomy Alzheimera objawiają się zanikami pamięci.
Lekkie symptomy Alzheimera objawiają się zanikami pamięci.
Może to prowadzić do powikłań zdrowotnych a nawet zgonu.
Może to prowadzić do powikłań zdrowotnych a nawet zgonu.

**Comment by PerzotProgrammer** [comment]
Pozdrawiam Perzot Programista.

**Comment by PerzotProgrammer** [comment]
fix'd
